id: I33AF3CB8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T22:13:07+00:00'
last_modified: '2022-06-10T06:22:01.586953+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21765
  title: ཐོག་ཁང་དམར་པོའི་རྨི་ལམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    9C42:
      image_group_id: I1KG21234
      title: Volume 1 of thog khang dmar po'i rmi lam/
      total_pages: 274
      order: 1
      base_file: 9C42.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
